/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as RegisterIndexRouteImport } from './register/index'
<<<<<<< Updated upstream
import { Route as FinanceIndexRouteImport } from './finance/index'
=======
import { Route as CourseIndexRouteImport } from './course/index'
>>>>>>> Stashed changes
import { Route as AuthIndexRouteImport } from './auth/index'
import { Route as AIIndexRouteImport } from './AI/index'
import { Route as CourseLessonIndexRouteImport } from './course/lesson/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< Updated upstream
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
=======
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
>>>>>>> Stashed changes
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AIIndexRoute = AIIndexRouteImport.update({
  id: '/AI/',
  path: '/AI/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseLessonIndexRoute = CourseLessonIndexRouteImport.update({
  id: '/course/lesson/',
  path: '/course/lesson/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AI': typeof AIIndexRoute
  '/auth': typeof AuthIndexRoute
<<<<<<< Updated upstream
  '/finance': typeof FinanceIndexRoute
=======
  '/course': typeof CourseIndexRoute
>>>>>>> Stashed changes
  '/register': typeof RegisterIndexRoute
  '/course/lesson': typeof CourseLessonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AI': typeof AIIndexRoute
  '/auth': typeof AuthIndexRoute
<<<<<<< Updated upstream
  '/finance': typeof FinanceIndexRoute
=======
  '/course': typeof CourseIndexRoute
>>>>>>> Stashed changes
  '/register': typeof RegisterIndexRoute
  '/course/lesson': typeof CourseLessonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AI/': typeof AIIndexRoute
  '/auth/': typeof AuthIndexRoute
<<<<<<< Updated upstream
  '/finance/': typeof FinanceIndexRoute
=======
  '/course/': typeof CourseIndexRoute
>>>>>>> Stashed changes
  '/register/': typeof RegisterIndexRoute
  '/course/lesson/': typeof CourseLessonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< Updated upstream
  fullPaths: '/' | '/AI' | '/auth' | '/finance' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/AI' | '/auth' | '/finance' | '/register'
  id: '__root__' | '/' | '/AI/' | '/auth/' | '/finance/' | '/register/'
=======
  fullPaths: '/' | '/AI' | '/auth' | '/course' | '/register' | '/course/lesson'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/AI' | '/auth' | '/course' | '/register' | '/course/lesson'
  id:
    | '__root__'
    | '/'
    | '/AI/'
    | '/auth/'
    | '/course/'
    | '/register/'
    | '/course/lesson/'
>>>>>>> Stashed changes
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AIIndexRoute: typeof AIIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
<<<<<<< Updated upstream
  FinanceIndexRoute: typeof FinanceIndexRoute
=======
  CourseIndexRoute: typeof CourseIndexRoute
>>>>>>> Stashed changes
  RegisterIndexRoute: typeof RegisterIndexRoute
  CourseLessonIndexRoute: typeof CourseLessonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< Updated upstream
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceIndexRouteImport
=======
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseIndexRouteImport
>>>>>>> Stashed changes
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AI/': {
      id: '/AI/'
      path: '/AI'
      fullPath: '/AI'
      preLoaderRoute: typeof AIIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/lesson/': {
      id: '/course/lesson/'
      path: '/course/lesson'
      fullPath: '/course/lesson'
      preLoaderRoute: typeof CourseLessonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AIIndexRoute: AIIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
<<<<<<< Updated upstream
  FinanceIndexRoute: FinanceIndexRoute,
=======
  CourseIndexRoute: CourseIndexRoute,
>>>>>>> Stashed changes
  RegisterIndexRoute: RegisterIndexRoute,
  CourseLessonIndexRoute: CourseLessonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
